import type { TargetCompany } from '../types';

export const DEFAULT_COMPANIES: Omit<TargetCompany, 'id'>[] = [
  // Research Labs
  { name: 'OpenAI', category: 'research_lab', teamPageUrls: ['https://openai.com/about'] },
  { name: 'Anthropic', category: 'research_lab', teamPageUrls: ['https://www.anthropic.com/company'] },
  { name: 'Google DeepMind', category: 'research_lab', teamPageUrls: ['https://deepmind.google/about/'] },
  { name: 'Meta FAIR', category: 'research_lab', teamPageUrls: ['https://ai.meta.com/research/'] },
  { name: 'xAI', category: 'research_lab', teamPageUrls: ['https://x.ai/about'] },
  { name: 'Mistral', category: 'research_lab', teamPageUrls: ['https://mistral.ai/company/'] },
  { name: 'Cohere', category: 'research_lab', teamPageUrls: ['https://cohere.com/about'] },
  { name: 'AI2', category: 'research_lab', teamPageUrls: ['https://allenai.org/team'] },
  { name: 'Microsoft Research', category: 'research_lab', teamPageUrls: ['https://www.microsoft.com/en-us/research/people/'] },
  { name: 'Apple ML Research', category: 'research_lab', teamPageUrls: ['https://machinelearning.apple.com/'] },
  { name: 'NVIDIA Research', category: 'research_lab', teamPageUrls: ['https://www.nvidia.com/en-us/research/'] },
  // AI-Native Products
  { name: 'Perplexity', category: 'ai_product', teamPageUrls: [] },
  { name: 'Cursor', category: 'ai_product', teamPageUrls: [] },
  { name: 'Lovable', category: 'ai_product', teamPageUrls: [] },
  { name: 'Bolt', category: 'ai_product', teamPageUrls: [] },
  { name: 'Replit', category: 'ai_product', teamPageUrls: [] },
  { name: 'Vercel', category: 'ai_product', teamPageUrls: [] },
  { name: 'Midjourney', category: 'ai_product', teamPageUrls: [] },
  { name: 'Runway', category: 'ai_product', teamPageUrls: [] },
  { name: 'ElevenLabs', category: 'ai_product', teamPageUrls: [] },
  { name: 'Stability AI', category: 'ai_product', teamPageUrls: [] },
  { name: 'Character.ai', category: 'ai_product', teamPageUrls: [] },
  { name: 'Inflection', category: 'ai_product', teamPageUrls: [] },
  { name: 'Adept', category: 'ai_product', teamPageUrls: [] },
  { name: 'Harvey', category: 'ai_product', teamPageUrls: [] },
  { name: 'Glean', category: 'ai_product', teamPageUrls: [] },
  { name: 'Sierra', category: 'ai_product', teamPageUrls: [] },
  // Infrastructure
  { name: 'Hugging Face', category: 'infrastructure', teamPageUrls: [] },
  { name: 'Scale AI', category: 'infrastructure', teamPageUrls: [] },
  { name: 'Weights & Biases', category: 'infrastructure', teamPageUrls: [] },
  { name: 'LangChain', category: 'infrastructure', teamPageUrls: [] },
  { name: 'Databricks', category: 'infrastructure', teamPageUrls: [] },
  { name: 'Together AI', category: 'infrastructure', teamPageUrls: [] },
  { name: 'Fireworks AI', category: 'infrastructure', teamPageUrls: [] },
  { name: 'Groq', category: 'infrastructure', teamPageUrls: [] },
  { name: 'Cerebras', category: 'infrastructure', teamPageUrls: [] },
  { name: 'Modal', category: 'infrastructure', teamPageUrls: [] },
  // Robotics
  { name: 'Figure', category: 'robotics', teamPageUrls: [] },
  { name: '1X', category: 'robotics', teamPageUrls: [] },
  { name: 'Physical Intelligence', category: 'robotics', teamPageUrls: [] },
  { name: 'Boston Dynamics', category: 'robotics', teamPageUrls: [] },
  { name: 'Tesla', category: 'robotics', teamPageUrls: [] },
];
